export const QUESTIONNAIR_ANSWER = 'QUESTIONNAIR_ANSWER';
export const QUESTIONNAIR_QUESTION_PICK = 'QUESTIONNAIR_QUESTION_PICK';
export const QUESTIONNAIR_QUESTIONS_ADD = 'QUESTIONNAIR_QUESTIONS_ADD';
