export const QUESTIONNAIR_ANSWER = 'QUESTIONNAIR_ANSWER';
export const QUESTIONNAIR_QUESTION_PICK = 'QUESTIONNAIR_QUESTION_PICK';
export const QUESTIONNAIR_QUESTIONS_SUCCESS = 'QUESTIONNAIR_QUESTIONS_ADD';
export const QUESTIONNAIR_QUESTIONS_FETCH = 'QUESTIONNAIR_QUESTIONS_FETCH';
export const QUESTIONNAIR_LIFELINE_50_50 = 'QUESTIONNAIR_LIFELINE_50_50';
export const QUESTIONNAIR_LIFELINE_10_SEC = 'QUESTIONNAIR_LIFELINE_10_SEC';
